import {Component, OnInit} from '@angular/core';
import {IHierarchyScope} from "../@core/model/hs";
import {HttpClient} from "@angular/common/http";
import {MessageService} from "../@core/data/message.service";
import {AppService} from "../@core/data/app.service";

@Component({
  selector: 'auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css'],
  providers:[AppService]
})
export class AutoGeneratedComponent implements OnInit {

  iHierarchyScope:IHierarchyScope[] = [];

  constructor(
    private http: HttpClient,
    private messageService: MessageService,
    private appService:AppService
    ) { }

  ngOnInit() {
    this.getHss();
  }

  getHss():void{
    this.appService.getHss()
      .subscribe(iHierarchyScope=>{
        console.log(iHierarchyScope);
        this.iHierarchyScope = iHierarchyScope;
      });
  }

}
